name: "Deploy Rust Docs to GitHub Pages"

on:
  push:
    tag: [v*]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}      
 
      - name: Setup Rust environment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build documentation
        run: cargo doc --lib --no-deps
        
      - name: Copy documentation files
        run: |
          cp -r target/doc/ ~/docs/
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Copy documentation files
        run: |
          mkdir -p docs
          cp -r ~/docs/* docs/
      
      - name: Add and commit changes
        run: |
          cd docs
          git add .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Update documentation"
      
      - name: Push to gh-pages branch
        run: |
          git push origin HEAD:gh-pages
